[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://smartpos-ai.netlify.app/.netlify/functions/backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/backend"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"