# fly.toml app configuration file generated for smartpos-ai-backend

app = "smartpos-ai-backend"
primary_region = "iad"

[build]

[env]
  MONGODB_URL = "mongodb+srv://hitmanacc001_db_user:Rlyq0PNiOyglNASp@cluster0.8otfoya.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
